### ISSUE TITLE
No ingress address

### ISSUE THREAD

**Issue by uriafranko** [unionai-oss/deploy-flyte#3]
Hey guys,

After fixing a few barriers I've managed to get the cluster up and running with the `flyte-binary` in running and healthy mode..

But I cannot get the ingress address:
![CleanShot 2023-09-10 at 18 10 34](https://github.com/unionai-oss/deploy-flyte/assets/44477558/3a945ba1-f177-4f68-ac6f-c9d6ad7c3807)

My helm config:
```yaml
configuration:
  inlineSecretRef: flyte-binary-inline-config-secret
  database:
    username: flyteadmin
    host: 'example'
    dbname: flyteadmin
  storage:
    metadataContainer: flyte-staging-data
    userDataContainer: flyte-staging-data
    provider: s3
    providerConfig:
      s3:
        region: 'eu-central-1'
        authType: 'iam'
  logging:
    level: 5
    plugins:
      cloudwatch:
        enabled: true
        templateUri: |-
          https://console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/eks/opta-development/cluster;stream=var.log.containers.{{ .podName }}_{{ .namespace }}_{{ .containerName }}-{{ .containerId }}.log
  auth:
    enabled: true
    oidc:
      baseUrl: https://accounts.google.com
      clientId: itsmysecret
      clientSecret: mysecretasswell
    internal:
      clientSecret: example
      clientSecretHash: has example
    authorizedUris:
      - https://flyte.dev.example
  inline:
    cluster_resources:
      customData:
        - production:
            - defaultIamRole:
                value: arn:aws:iam::example:role/flyte-staging-flyte-worker
        - staging:
            - defaultIamRole:
                value: arn:aws:iam::example:role/flyte-staging-flyte-worker
        - development:
            - defaultIamRole:
                value: arn:aws:iam::example:role/flyte-staging-flyte-worker
    flyteadmin:
      roleNameKey: 'iam.amazonaws.com/role'
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - AWS_METADATA_SERVICE_TIMEOUT: 5
          - AWS_METADATA_SERVICE_NUM_ATTEMPTS: 20

    storage:
      cache:
        max_size_mbs: 10
        target_gc_percent: 100
    tasks:
      task-plugins:
        enabled-plugins:
          - container
          - sidecar
          - K8S-ARRAY
        default-for-task-types:
          - container: container
          - container_array: K8S-ARRAY
    task_resources:
      defaults:
        cpu: 1
        memory: 1Gi
        storage: 100Mi

clusterResourceTemplates:
  inline:
    001_namespace.yaml: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ namespace }}'

    002_serviceaccount.yaml: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: default
        namespace: '{{ namespace }}'
        annotations:
          eks.amazonaws.com/role-arn: '{{ defaultIamRole }}'

ingress:
  create: true
  commonAnnotations:
    kubernetes.io/ingress.class: nginx
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:eu-central-1:example...'
  httpAnnotations:
    nginx.ingress.kubernetes.io/app-root: /console
  grpcAnnotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  host: flyte.dev.example

rbac:
  extraRules:
    - apiGroups:
        - ''
      resources:
        - pods
        - services
        - configmaps
      verbs:
        - '*'
    - apiGroups:
        - ''
      resources:
        - serviceaccounts
      verbs:
        - create
        - get
        - list
        - patch
        - update
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - rolebindings
        - roles
      verbs:
        - create
        - get
        - list
        - patch
        - update

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::example

```
