### ISSUE TITLE
Nodes - Pods Tolerations

### ISSUE THREAD

**Issue by uriafranko** [unionai-oss/deploy-flyte#4]
After getting a few things to work it seems that the tolerations of the nodes include:
`flyte.org/node-role = worker` but the pods scheduled by flyte do not include them, any idea how to fix it?

![CleanShot 2023-09-12 at 11 50 29](https://github.com/unionai-oss/deploy-flyte/assets/44477558/f9adc689-d97a-492f-9bc4-5c0882da8a74)

**Comment by uriafranko** [comment]
Adding the following lines helped...

```yaml
default-tolerations:
  - key: 'flyte.org/node-role'
    operator: 'Equal'
    value: 'worker'
    effect: 'NoSchedule'
```

**Ended up at:** 

![CleanShot 2023-09-12 at 12 27 32@2x](https://github.com/unionai-oss/deploy-flyte/assets/44477558/e662d1ae-ed05-445e-9ea1-e91b0c6c40e9)

**Comment by uriafranko** [comment]
Fixed after manually installing nvidia-device-plugin in the cluster with those settings:
```yaml
tolerations:
  - key: 'nvidia.com/gpu'
    effect: 'NoSchedule'
    value: 'present'
  - key: 'flyte.org/node-role'
    operator: 'Equal'
    value: 'worker'
    effect: 'NoSchedule'

```

Now the `nvidia/gpu` is exposed but for some reason, the nvidia pods try to init on non-gpu nodes aswell...

**Comment by davidmirror-ops** [comment]
@uriafranko Fixed. I changed the `taints` map on the `eks` module. Labels are still there, they are maybe useful for filtering, also GPU taints are still there, but no `flyte-node=worker` .

Thanks

**Comment by qchenevier** [comment]
> Fixed after manually installing nvidia-device-plugin in the cluster with those settings:
> 
> ```yaml
> tolerations:
>   - key: 'nvidia.com/gpu'
>     effect: 'NoSchedule'
>     value: 'present'
>   - key: 'flyte.org/node-role'
>     operator: 'Equal'
>     value: 'worker'
>     effect: 'NoSchedule'
> ```
> 
> Now the `nvidia/gpu` is exposed but for some reason, the nvidia pods try to init on non-gpu nodes aswell...

For people facing the same issue, to install the nvidia-device-plugin, it's an additional helm install in the k8s cluster (addtionally to the flyte installation with helm). Here is [how to install it with helm](https://github.com/NVIDIA/k8s-device-plugin#deployment-via-helm).

And in order to avoid having the nvidia-device-plugin being deployed on non-GPU nodes (and being shown as a pod in `CrashLoopBackoff`), you can add a _nodeSelector_ in the nvidia-device-plugin configuration like this:
```yaml
nodeSelector: 
  k8s.amazonaws.com/accelerator: nvidia-tesla-t4  # pick a label which is specific to your GPU nodes, to select them
```

---

In the end, my config file (called `nvidia-device-plugin-values.yaml`) looks like that:
```yaml
nodeSelector: 
  k8s.amazonaws.com/accelerator: nvidia-tesla-t4
tolerations:
  - key: 'nvidia.com/gpu'
    effect: 'NoSchedule'
    value: 'present'
  - key: 'flyte.org/node-role'
    operator: 'Equal'
    value: 'worker'
    effect: 'NoSchedule'
```

And I triggered the plugin install with that file:
```bash
helm install nvdp nvdp/nvidia-device-plugin --version=0.14.1 --namespace nvidia-device-plugin --create-namespace --values=nvidia-device-plugin-values.yaml
```
