### ISSUE TITLE
Cloudwatch not getting logs.

### ISSUE THREAD

**Issue by uriafranko** [unionai-oss/deploy-flyte#5]
Hey again :)

The logs are not getting into the CloudWatch for some reason.

Logs section in the helm file
``` yaml 
logging:
    level: 4 (tried also 1)
    plugins:
      cloudwatch:
        enabled: true
        templateUri: |-
          https://console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/aws/eks/flyte-staging/cluster;stream=var.log.containers.{{ .podName }}_{{ .namespace }}_{{ .containerName }}-{{ .containerId }}.log
 ```
 
 CloudWatch can't find the log stream:
 
![CleanShot 2023-09-21 at 17 28 04](https://github.com/unionai-oss/deploy-flyte/assets/44477558/dd7e4d43-71f8-4825-94f8-7d58550f792b)

Looking at the other log streams it seems that most of the pods get log streams but none of the workflow/tasks get them.

Any idea what is not configured right? (tried adding CloudWatch full access policy to the role as well)
